public enum Relationship {
    FATHER, MOTHER, SON, DAUGHTER,
    GRANDFATHER, GRANDMOTHER,
    GRANDSON,
    GRANDDAUGHTER,
    HUSBAND, WIFE,
    MOTHERINLAW, FATHERINLAW,
    DAUGHTERINLAW, NEPHEW, BROTHERINLAW,
    BROTHER, SISTER
}
